eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: User
  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      host: localhost
      port: 27017
      database: jwt_security



